server: backport maps command implementation from old engine
FWGS/xash3d-fwgs pull request #460
Opened 2021-05-29 18:33 UTC by tyabus

2021-05-30 18:47 UTC, lewa-j commented on engine/server/sv_cmds.c
> +	char mapName[256], *seperator = "-------------------";
Non-const pointer to string literal here.

2021-05-30 18:50 UTC, lewa-j commented on engine/server/sv_cmds.c
> +        mapList = FS_Search(va("maps/*%s*.bsp", argStr), false, true);
Please do uniform indentation.

2021-06-01 19:08 UTC, a1batross requested changes

2021-06-01 19:08 UTC, a1batross commented on engine/server/sv_cmds.c
> +		Q_strncpy( (char*)mapName, mapList->filenames[listIndex], sizeof( mapName ) - 1 );
Зачем? Просто задефайни `mapName` как обычный массив `char`. Или лучше вообще воспользуйся `string`.

Так же не нужно делать `sizeof() - 1` в `Q_strncpy`, он всегда проставляет null в конце строки.

2021-06-01 19:08 UTC, a1batross commented on engine/server/sv_cmds.c
> +	mapList = FS_Search( va( "maps/*%s*.bsp", argStr ), false, true );
caseinsensitive можно и в true выставить.

2021-06-01 19:08 UTC, a1batross commented on engine/server/sv_cmds.c
> +	Msg( "%s\n", seperator );
separator

2021-06-01 19:08 UTC, a1batross commented on engine/server/sv_cmds.c
> +		if( ( Q_strcmp( argStr, "*" ) == 0 ) || ( Q_stristr( mapName, argStr ) != NULL ) )
Зачем эта проверка?

2021-06-02 04:24 UTC, lewa-j commented on engine/server/sv_cmds.c
> +	const char mapName[256], *seperator = "-------------------";
const нужен был для separator но не для mapName

2021-06-02 16:47 UTC, lewa-j commented on engine/server/sv_cmds.c
> +	Msg( "%s\n", seperator );
sep**A**rator

2021-06-03 04:35 UTC, lewa-j commented on engine/server/sv_cmds.c
> +		Msg( "%s\n", &mapName[5] ); // Do not show "maps/"
Вместо этих двух строк:
`Msg( "%s\n", mapList->filenames[listIndex] + 5 ); // Do not show "maps/"`
И от mapName можно избавиться

2021-06-03 06:18 UTC, nekonomicon commented on engine/server/sv_cmds.c
> +		Msg( "%s\n", &mapName[5] ); // Do not show "maps/"
mapName можно сделать указателем для читаемости.

2021-06-06 23:31 UTC, a1batross requested changes

2021-06-06 23:31 UTC, a1batross commented on engine/server/sv_cmds.c
> +		Msg( "%s\n", mapList->filenames[listIndex] + 5 ); // Do not show "maps/"
А что если "maps/" нет, а мы читаем за границей массива?

FS_Search конечно такое не вернет, но мало ли. Ну вдруг?

2021-06-07 00:38 UTC, nekonomicon commented on engine/server/sv_cmds.c
> +		Msg( "%s\n", mapList->filenames[listIndex] + 5 ); // Do not show "maps/"
Вообще наверно стоит по аналогии с SOUND_FOLDER задефайнить где-нибудь MAPS_FOLDER и считать размер в compile-time для читабельности, ну и как я до этого писал mapName сделать указателем.

2021-06-17 15:50 UTC, nekonomicon commented on engine/server/sv_cmds.c
> +TODO: Make it more convenient. (Timestamp check, temporary file, ...)
Я думаю TODO можно отсюда убрать.

2021-06-17 15:52 UTC, nekonomicon commented on engine/server/sv_cmds.c
> +	Msg( "%s\nDirectory: \"%s/maps\" - Maps listed: %d\n", separator, GI->basedir, mapList->numfilenames );
Разделитель можно вставить в строку как есть либо сделать макросом
```
Msg( SEPARATOR "\nDirectory: \"%s/maps\" - Maps listed: %d\n",  GI->basedir, mapList->numfilenames );
```

2021-06-17 15:55 UTC, nekonomicon commented on engine/server/sv_cmds.c
> +		Msg( "Usage: maps <substring>\nmaps * for full listing\n" );
Здесь можно использовать макрос S_USAGE
https://github.com/FWGS/xash3d-fwgs/blob/master/engine/common/com_strings.h#L23

2021-06-17 16:04 UTC, nekonomicon commented on engine/server/sv_cmds.c
> +		Msg( "%s\n", mapList->filenames[listIndex] + 5 ); // Do not show "maps/"
Здесь определен макрос DEFAULT_SOUNDPATH https://github.com/FWGS/xash3d-fwgs/blob/master/engine/common/com_strings.h#L49
Можно по аналогии объявить макрос DEFAULT_MAPSPATH и сделать так:
```
const char *mapName;
```

```
mapName = mapList->filenames[listIndex];
Msg( "%s\n", mapName[sizeof( DEFAULT_MAPSPATH )  - 1] );  
```
А строку поиска изменить так:
```
DEFAULT_MAPSPATH "*%s*.bsp"
```

2021-06-17 21:07 UTC, a1batross commented
Замержил, но всё-таки переписал.

У нас уже есть вывод списка карт через функцию автодополнения map, поэтому зачем разводить копипасту. Да и это автодополнение всякую полезную информацию выдаёт: версия карты, компилятор и так далее.

2021-06-17 21:07 UTC, closed without merging