engine: Haiku BeGameLauncher support
FWGS/xash3d-fwgs pull request #483
Opened 2021-06-05 14:47 UTC by exstrim401

https://github.com/EXL/BeGameLauncher

2021-06-06 12:54 UTC, a1batross commented
What MIRRORDIR does?

To be honest, I don't remember specifics of Haiku port by EXL but to me this doesn't look right.
If I'm not wrong, MIRRORDIR is another layer for filesystem? Today we have RoDir for that.

2021-06-07 12:50 UTC, exstrim401 commented
I also made XASH3D_GAME env available for all platforms to choose game at start

2021-06-07 14:35 UTC, a1batross requested changes

2021-06-07 14:35 UTC, a1batross commented on game_launch/game.cpp
> +	char *game = getenv( E_GAME  );
make it `const char` please, so we won't lose const modifier two lines below. Otherwise lgtm

2021-06-07 16:39 UTC, merged