Resource Manager
FWGS/xash3d-fwgs pull request #729
Opened 2022-01-14 00:50 UTC by zgdump

## Менеджер текстур

Последний рабочий коммит - 697f3b38c0138be74e1b0df244d2cb1bc1c56ffa
В последнем преднамеренно сделан краш

### Цель

Данный PR нацелен на создание менеджера текстур для упрощения рендеров и избавления от дублирующего кода

### Мотивация

Впервые с необходимостью в отдельном менеджере я столкнулся при переключении рендера на лету. Перезагрузка ресурсов, в частности, текстур -- краеугольный камень для смены рендера без перезапуска движка. В [своём черновике](https://github.com/w23/xash3d-fwgs/pull/66) для принудительного обновления текстур были применены грязные хаки с флагами и отключением важных проверок. Желая избавится от них была начата работа в этом направлении

### Перспектива

Менеджер преимущественно разрабатывается на перспективу.
В недалёком будущем планируется:
- Вынос системы патчей материалов из [ref_vk](https://github.com/w23/xash3d-fwgs) в менеджер ресурсов
- Реализовать переключение рендеров. Meta issue с обобщением опыта будет в скором времени
- Доработать менеджер текстур до полноценного менеджера ресурсов 

### План

Работу планирую разделить на два глобальных этапа

#### Этап 1

Этап нацелен на создание дублирующего слоя: менеджера текстур, работающего полностью идентично текущему

- [x] Создать прокси между движком и рендером, для последующей реализации менеджера текстур 
- [x] Повторить загрузку, хранение текстур
- [ ] Повторить генерацию текстур-заглушек из рендера
- [ ] Восстановить недостающий код флагов
- [ ] Восстановить недостающий код мипов
- [ ] Починить сломанные спрайты

#### Этап 2

Этап нацелен на фиксы и облегчение ref_gl. Этот рендер стабилен, реализует все возможности движка 

- [ ] Удалить хранение текстур
- [ ] Удалить генерацию текстур-заглушек
- [ ] Перенести загрузку спрайтов в движок
- [ ] ???
...

Второй этап может выполняться параллельно с первым. Но потребует чужой помощи. Я не разбираюсь в рендерах. И патчинг ref_gl займёт у меня времени больше, чем у знающего человека

### Как это всё выглядит сейчас?

Как-то так... Нужно чинить спрайты, вынося Mod_ProcessRenderData в двиг.

![image](https://user-images.githubusercontent.com/60278551/149431984-42f1583f-f373-48f4-98b9-a45016b14a0d.png)

![image](https://user-images.githubusercontent.com/60278551/149432122-b6d58969-adbf-4847-a900-f45abe0b5b21.png)

2022-01-14 00:53 UTC, SNMetamorph commented
Это как-то повлияет на рендеры, реализованные внутри клиентской игрокой библиотеки через RenderAPI?

2022-01-14 00:55 UTC, zgdump commented
> Это как-то повлияет на рендеры, реализованные внутри клиентской игрокой библиотеки через RenderAPI?

Возможно, повлияет. Не думал, не тестировал. Если требуется, протестирую и поддержу

2022-01-14 01:00 UTC, 0x4E69676874466F78 commented
@SNMetamorph рендеры наверное зовут что-то типа ref.dllFuncs.GL_LoadTexture? тогда менеджер текстур по идее это перехватывает.

2022-01-14 01:01 UTC, zgdump commented
На текущий момент, я лишь проксирую вызовы из движка к рендеру. По сути, дублируя код из оного. Но скоро и render api будет проксироваться, а совместимость ref api может быть нарушена

2022-01-14 03:53 UTC, zgdump commented
Эксперименты в mainui попали в данный PR случайно

2022-01-14 04:03 UTC, zgdump commented
Сейчас глитчи с текстурами стен происходят из-за расхождения texnum в рендере и моём менеджере текстур. Расхождение возникает из-за функции `Mod_ProcessRenderData`, которая подгружает текстуры спрайтов. Если её захачить, то глитчи уходят, но и весь движок падает через несколько секунд

![image](https://user-images.githubusercontent.com/60278551/149448775-f5f9c7db-8ca3-42ed-83fb-fc5279fe57a1.png)

Я вижу несколько сценариев, как поступать с функцией `Mod_ProcessRenderData`.

**Первый**. Закрыть глаза на глитчи, мёрж сделать в отдельную ветку `resman`. И при дальнейшей реализации вынести загрузку спрайтов в двиг, за одно решив эту проблему

**Второй**. Вытащить функцию и всё ей сопутствующее в двиг, превратив PR в `Resource Manager`. Я попытался на скорую руку, но там очень много кода. Неизвестно, что ещё придётся распутать

**Третий**. Пока что захачить texnum, чтобы он всегда был идентичен рендеровскому до тех пор, пока не будет удалён менеджер текстур в рендере

**Четвёртый**. Добавить методы менеджера ресурсов в `gEngfuncs`, пропатчив рендер так, чтобы он подгружал текстуры через двиг, а не напрямую в себя. Тупо, но практично

2022-01-14 04:08 UTC, zgdump commented
В каком состоянии находится функция `Mod_ProcessRenderData`? Часть веток закомментированна без комментариев. Саму функцию дёргают непонятно кто и непонятно откуда в больших количествах. Я не могу распутать клубок вызовов(

![image](https://user-images.githubusercontent.com/60278551/149449771-6ce086f9-52e9-4c59-b773-511f6bc549b8.png)

При смене рендера я всё это хачил. Много, муторно, методично. Сейчас же хочу разобраться и сделать более-менее красиво

2022-01-14 04:09 UTC, zgdump commented
Дополнительно отмечу, что где-то утекает ref_api.h. Если его подключить несколько раз подряд, случается такое на несколько экранов:

![image](https://user-images.githubusercontent.com/60278551/149449994-616de5d7-c541-4524-99fa-e3aaeffbb746.png)

2022-01-14 10:15 UTC, a1batross commented
Лучше за основу как раз брать ref_gl, а ref_vk уже подпиливать. Я в целом пока рекомендую забить на существование ref_vk, неизвестно насколько корректно он реализован.

Mod_ProcessRenderData исключительно рендероспецифичная. То что она наполовину закомментирована ничего страшного -- значит ничего делать. Вызывается при загрузке и выгрузке модели.

2022-01-14 14:54 UTC, zgdump commented
> Лучше за основу как раз брать ref_gl, а ref_vk уже подпиливать. Я в целом пока рекомендую забить на существование ref_vk, неизвестно насколько корректно он реализован

За основу взят общий код для обоих рендеров

> Mod_ProcessRenderData исключительно рендероспецифичная. То что она наполовину закомментирована ничего страшного -- значит ничего делать. Вызывается при загрузке и выгрузке модели.

Понял. Как мне лучше поступить с ней? Четыре сценария изложил выше

2022-01-15 00:08 UTC, a1batross commented
Ничего не делать. Это загрузка моделей, она не связана с текстурами.

Возможно, лучше завести новый коллбэк, который будет оповещать рендер что пора загрузить текстуру в видеопамять и присвоить ей рендероспецифичный handle.

2022-01-15 00:28 UTC, zgdump commented
> Ничего не делать. Это загрузка моделей, она не связана с текстурами.

Вы не правы. При загрузке моделей происходит загрузка и текстур через функцию R_SpriteLoadFrame (см. `gl_sprite.c:50`). Происходит это в обход движка. И именно это я пытаюсь решить. То ли хачить пока не поправлю рендер, то ли прокидывать менеджер ресурсов в рендер

2022-01-15 00:33 UTC, a1batross commented
Ничего там в обход не происходит. У тебя уже есть LoadTexture в движке, пусть он движковый и вызывает.

2022-01-16 01:05 UTC, zgdump commented
После коммита d50edac ушли глитчи из меню в рендере ref_soft. Сами уровни не запускал, ибо ref_soft не работает на x64 и пока не удалось его пропатчить

![image](https://user-images.githubusercontent.com/60278551/149643339-d67129f7-a4ba-43bf-b63e-0165f5e43e8b.png)

2022-01-16 01:08 UTC, zgdump commented
После коммита 54fc8a0 починились лайтмапы на GL

![image](https://user-images.githubusercontent.com/60278551/149643388-a6867898-e608-4af0-9b5d-fdffda030041.png)

На карте test_brush всё ещё наблюдаются глитчи. Надо гонять статические анаизаторы и санитайзеры. Похоже на утечку памяти, коих на этой карте стреляет очень много на ref_vk

2022-01-16 01:09 UTC, zgdump commented
Возможно, всё же, где то поплыли индексы, судя по редким глитчам в меню. По логам не вижу, буду исследовать позднее, в процессе патчей ref api

2022-01-16 01:58 UTC, zgdump commented
Удалось зафиксить ref_soft на x64, успешно работает с менеджером текстур. PR с отдельной веткой скоро будет 

![image](https://user-images.githubusercontent.com/60278551/149644358-dcfffa13-03c6-48d3-a55e-374b4dcc283e.png)

2022-01-16 07:03 UTC, a1batross commented
Как полностью удалишь менеджер текстур из ref_gl, то и индексы начнут совпадать.

Дело все в том, что загрузка текстур в нём почему-то игнорирует вызов glCreateTextures и в качестве texnum берёт порядковый номер загруженной текстуры. Про это поведение в спеках OpenGL я находил целое ничего, так что удивительно что оно вообще работает.

2022-01-16 08:22 UTC, zgdump commented
> Как полностью удалишь менеджер текстур из ref_gl, то и индексы начнут совпадать

Они и сейчас должны совпадать. Но я согласен, что после удаления проблема уйдёт точно. Надеюсь, в ближайшие пару дней у меня получится придти к этому. Сначала нужно перенести текстуры-заглушки, флаги и поправить работу с хэш мапой

> Дело все в том, что загрузка текстур в нём почему-то игнорирует вызов glCreateTextures и в качестве texnum берёт порядковый номер загруженной текстуры. Про это поведение в спеках OpenGL я находил целое ничего, так что удивительно что оно вообще работает

Повеселил! Хоть не я один не понимаю, что вообще происходит в рендере и как оно работает

А ведь я хочу перед сменой рендера ещё попытаться в ref_common...

2022-01-16 08:30 UTC, zgdump commented
> Дело все в том, что загрузка текстур в нём почему-то игнорирует вызов glCreateTextures и в качестве texnum берёт порядковый номер загруженной текстуры. Про это поведение в спеках OpenGL я находил целое ничего, так что удивительно что оно вообще работает

Иван @w23 ответил следующее:

https://www.khronos.org/registry/OpenGL/specs/gl/glspec21.pdf раздел 3.8.12, страница 182 (196 в пдф)
> The name space for texture objects
>is the unsigned integers, with zero reserved by the GL.
> A texture object is created by binding an unused name to TEXTURE 1D,
> TEXTURE 2D, TEXTURE 3D, or TEXTURE CUBE MAP.

glCreateTextures издревле был не то, чтобы очень нужен. это просто соломка, если тебе влом самому за интами следить

2022-04-23 18:08 UTC, zgdump commented
Спустя продолжительный перерыв вернулся к работе над PR.

В коммите 8b2e6f3 я объединил сразу несколько важных изменений:
- Удаление менеджмента текстур из `ref_gl`
Теперь API упрощено до методов загрузки и удаления текстуры по индексу, всем прочим занят менеджер
Пока пришлось выключить `ref_soft`, ибо он не адаптирован под изменения.
- Переработка хэш таблицы в менеджере текстур
Изначально реализация была перенесена из рендера, но с ней были странные проблемы. Проще было написать свою несложную, чем выяснять-чинить
- Реализация удаления текстур в менеджере

Всё в совокупности дало результат, идентичный натуральному. Ничего не падает, явным образом не глитчует.

Остаются проблемы:
- Не реализованы текстуры-заглушки
- Не перенесены флаги
- Не вынесены хитрые манипуляции в менеджер текстур

Теперь нужно решить, как тестировать реализацию. @a1batross, подскажи, пожалуйста, как выявить регрессии? Временно использую тестовые карты от @0x4E69676874466F78, но и они не абсолют

2022-04-24 12:42 UTC, a1batross commented
@zgdump тестирование на регрессии у нас нет.

Сейчас ручная работа. Берёшь порт, берёшь мод и тестируешь. Впрочем, если в Half-Life, PrimeXT, Paranoia 2 всё в порядке, то высока вероятность что заработает скорее всего везде.

2022-04-24 13:11 UTC, nekonomicon commented
Навскидку можно пробежать моды под GS и под ксашем из этого списка:
https://pastebin.com/tJseQ7PG

2022-05-04 00:20 UTC, zgdump commented
После реализации стандартных текстур, внезапно, стало очень хорошо. Ушли ошибки, пропали глитчи с лайтмап. Во текущем виде, менеджер текстур достаточно стабилен, основные задачи выполнены

![image](https://user-images.githubusercontent.com/60278551/166605932-9e3a6e68-a2dd-4081-9bbe-c71bd34f3e95.png)

Далее нужно пройти несколько игр на этой реализации, исправляя все найденные проблемы. Отрефакторить код, пройтись анализатором, починить утечки. И восстановить недостающие методы

2022-05-04 22:43 UTC, a1batross commented
Да, встроенные текстуры важны. Важно ещё соблюдать им имена, но я их все вынес в RefAPI. 

Надо пожалуй перейти на твою ветку и дорабатывать её до мержабельного (от слова морж походу) состояния.

2022-05-05 07:49 UTC, zgdump commented
> Да, встроенные текстуры важны. Важно ещё соблюдать им имена, но я их все вынес в RefAPI.

В `ref_api.h` добавил ещё `*cintexture` и `*dlight`, почему-то они не были задефанены и в `ref_gl` использовались строками.

Из всех стандартных текстур не перенёс `solid_sky` и `alpha_sky`. Код для генерации в [gl_warp.c:652](https://github.com/FWGS/xash3d-fwgs/blob/master/ref_gl/gl_warp.c#L652). Испужался, оставил на когда-нибудь)

> Надо пожалуй перейти на твою ветку и дорабатывать её до мержабельного (от слова морж походу) состояния.

Про моржа не понял.
Если поможешь, буду крайне признателен. Тут нужны и тесты, и почин под linux (f ansient c), и напильник

2022-05-05 10:04 UTC, SNMetamorph commented
С текущей архитектурой менеджера текстур есть одна весомая проблема. Все текстуры хранятся в памяти, если, допустим, мод использует текстур на пару гигабайт, то всё это будет висеть в памяти игры просто ради того, чтобы рендер можно было менять на ходу. Мне кажется, стоит сделать это поведение конфигурируемым, далеко не всегда рационально жертвовать оперативной памятью ради горячей смены рендеров. Я предлагаю сделать возможность со стороны клиента игры отключить такое поведение, либо чтобы это конфигурировалось кваром.

2022-05-05 10:18 UTC, zgdump commented
Продублирую мысли, сформулированные в Discord.

Хранение оригиналов текстур не моя идея. Так было сделано до меня в `ref_gl`, это же перекочевало в `ref_soft` и `ref_vk`. И это не просто архитектурное решение, но ий инвариант, на который полагается логика.

Для смены рендера оригиналы хранить вовсе не обязательно. Достаточно знать имена текстур. И при смене рендера они будут вновь прогружены из файловой системы

2022-05-05 10:23 UTC, zgdump commented
Я попробовал на скорую руку пропатчить `ref_gl` и убрать хранение оригинальной текстуры. Для этого мне пришлось:
- Захачить GL_ProcessTexture
- Захачить GL_ProcessImage
- Убрать метод GL_GetTextureOriginalBuffer из ref_api

И оно собралось, заработало, но буквально на первом повороте уровня `c1a1d` взорвалось в кишках:

![image](https://user-images.githubusercontent.com/60278551/166904752-18ea12ed-ad5d-4e35-a6ff-6d0e4ed1ad93.png)

Безусловно, уверен, всё можно изменить, поправить, исправить, закрыть глаза на патчи GAME_EXPORT функций. Вопрос трудозатрат

Как компромисс с @SNMetamorph могу сделать опцию для менедера текстур, чтобы оригинал отчищался сразу после загрузки, а в original хранился NULL

2022-05-05 11:48 UTC, a1batross commented
Хе-хе. Вы что-то не то делаете с хранением оригинальной текстуры или я вас неправильно понимаю.

Во-первых, гигабайты текстур мода и правда не должны храниться в оперативной памяти. Но есть один нюанс, о нём чуть позже.

Во-вторых, запрос хранения оригинала текстур исходит не от пользователя и даже не от разработчика мода, а от того кто пишет рендерер или собственно разрабатывает движок.

Есть у загрузчика флаг `TF_KEEP_SOURCE`. Где он используется вам расскажет код, но навскидку -- он нужен для ремаппинга палитры, баловства, типа чтобы вписывать номер билда в Quake и самое важное, тот самый нюанс о котором я говорил -- `ENGINE_IMPROVED_LINETRACE`. Это трейс через дырчатые текстуры. Это может занимать гигабайты, но разработчик мода сам запросил эту фичу движка и знал на что идёт, если хотел чтобы трейс, учитывал дырчатые текстуры, типа сеточек, заборов и прочего.

И только на этот флаг и надо ориентироваться. Задача же горячей смены рендерера -- это то, что нужно выделить за scope этого гигантского патча, а не пытаться решать всё подряд и запутываться в своём же собственном коде.

2022-05-05 13:21 UTC, zgdump commented
Выходит, это не magic, а вполне понятная логика:

```c
	// Bit magic
	if( FBitSet( flags, TF_NOFLIP_TGA ))
		SetBits( picFlags, IL_DONTFLIP_TGA );

	if( FBitSet( flags, TF_KEEP_SOURCE ) && !FBitSet( flags, TF_EXPAND_SOURCE ))
		SetBits( picFlags, IL_KEEP_8BIT );

	// Flags magic
	Image_SetForceFlags( picFlags );
```

2022-05-05 15:05 UTC, mittorn commented
Для ref_soft нужны будут текстуры оригинальные, а не в rgba, как их имиджлиба выдаёт, причём вместе с палитрой. Сейчас там используются rgba текстуры с заметным понижением качества и хитрой паковкой пикселя под это, но в халфе все текстуры кроме неба 8битные

2022-05-05 16:19 UTC, a1batross commented
Эти и другие задачи можно было бы решить уже после мержа (моржа!) движкового менеджера текстур.

2022-05-05 20:24 UTC, zgdump commented
Сделал правки для `ref_soft`, теперь корректно собирается и запускается под менеджером:

![image](https://user-images.githubusercontent.com/60278551/167019255-c2c7cb53-54b8-481d-bed9-d8f2a7c14fa8.png)

Для тестов мёржнул `master` в эту ветку, потом откатил изменения

2022-05-05 20:26 UTC, zgdump commented
Ещё продолжу работать над PR, но уже можно обзирать и критиковать

2022-05-09 10:15 UTC, zgdump commented
@a1batross помоги угадать, пожалуйста. В коридорчике на уровне `c1a0d` испортился потолок, не сходятся тайлы. И это наблюдаю только там, больше нигде глюков с тайловыми изображениями нет

![image](https://user-images.githubusercontent.com/60278551/167389739-536e891e-e528-4b2f-af5a-c2024027d0e0.png)

2022-07-02 19:39 UTC, 0x4E69676874466F78 commented
> В коридорчике на уровне c1a0d испортился потолок, не сходятся тайлы. И это наблюдаю только там, больше нигде глюков с тайловыми изображениями нет

На всякий случай сюда отпишу. Это из-за случайных тайловых текстур. Не важно динамическое или статическое зерно задано в движке, на c1a0d будет вот такой шов. Шов происходит из-за того что зерно попадает с такой комбинацией тайлов которые между собой плохо мостятся (это недоработка valve).

2022-07-14 11:58 UTC, 0x4E69676874466F78 commented
а что тут за freebsd какие-то сломанные?

2022-07-15 16:12 UTC, zgdump commented
@a1batross готово для ревью, критикуйте, обзирайте

2022-07-15 17:50 UTC, SNMetamorph commented
Что насчет вот этого?
> С текущей архитектурой менеджера текстур есть одна весомая проблема. Все текстуры хранятся в памяти, если, допустим, мод использует текстур на пару гигабайт, то всё это будет висеть в памяти игры просто ради того, чтобы рендер можно было менять на ходу. Мне кажется, стоит сделать это поведение конфигурируемым, далеко не всегда рационально жертвовать оперативной памятью ради горячей смены рендеров. Я предлагаю сделать возможность со стороны клиента игры отключить такое поведение, либо чтобы это конфигурировалось кваром.

2022-07-15 17:57 UTC, zgdump commented on engine/resman/texture.c
> +		if( !FBitSet( tex->flags, TF_IMG_UPLOADED ) && FBitSet( tex->flags, TF_KEEP_SOURCE ))
@SNMetamorph у текстуры существует флаг `TF_KEEP_SOURCE`, который как раз и отвечает, будет ли хранится текстура в памяти движка

2022-07-16 15:34 UTC, a1batross requested changes

2022-07-16 15:34 UTC, a1batross commented on engine/resman/texture.c
> +typedef struct rm_texture_s {
{ на новой строке

2022-07-16 15:34 UTC, a1batross commented on engine/resman/texture.c
> +		for (
Ненужный перенос строки.

2022-07-16 15:34 UTC, a1batross commented on engine/resman/texture.c
> +	status = Textures.ref->R_LoadTextureFromBuffer
Зачем эти переводы строк...

2022-07-16 15:34 UTC, a1batross commented on engine/resman/texture.c
> +	Textures.count--;
Как и в AppendTexture: count уменьшается, при этом будучи в рассинхроне с реальным последним занятым элементом массива.

2022-07-16 15:34 UTC, a1batross commented on engine/resman/texture.c
> +	const char* name = "*unused";
На всякий, названия лучше не будем менять, даже для dummy текстуры.

В оригинале она `*unused*`

2022-07-16 15:34 UTC, a1batross commented on engine/resman/texture.c
> +	r_image = malloc(sizeof(rgbdata_t));
Mem_Alloc!!!

2022-07-16 15:34 UTC, a1batross commented on engine/resman/texture.c
> +	r_image->buffer  = malloc(r_image->size);
Mem_Alloc!!!!!

2022-07-16 15:34 UTC, a1batross commented on engine/resman/texture.c
> +	for ( y = 0; y < 8; y++ )
y < h

2022-07-16 15:34 UTC, a1batross commented on engine/resman/texture.c
> +		for ( x = 0; x < 8; x++ )
x < w

2022-07-16 15:34 UTC, a1batross commented on engine/resman/texture.c
> +int CreateDlightTexture( void )
Стоит ли текстуру для dlight содержать в движке?

Это всё-таки механизм существующий только из-за ref_gl. Даже в ref_soft он только из-за копипасты.

2022-07-16 15:34 UTC, a1batross commented on engine/resman/texture.h
> +#ifndef RM_TEXTURE_H
GPL notice

2022-07-16 15:34 UTC, a1batross commented on engine/server/sv_phys.c
> +	return Host_IsDedicated() ? NULL : RM_TextureData( texnum );
В будущем конечно есть смысл текстуры грузить и в сервере, так как Ксаш например поддерживает трейсы сквозь дырчатые текстуры.

Ну да ладно. :)

2022-07-16 15:34 UTC, a1batross commented on engine/wscript
> +		'resman/*.c'])
Не могу комментарий поставить на сабмодуль. Верни mainui.

Вообще, предлагаю не делать git merge, а ребейзить свои изменения поверх текущего мастера. Так история чище, merge даже отключён в настройках репозитория.

2022-07-16 15:34 UTC, a1batross commented on ref_gl/gl_image.c
> -/*
Куда все комментарии дел? :)

2022-07-16 15:34 UTC, a1batross commented on ref_gl/gl_image.c
> +	gl_texture_t *tex = &(gl_textures[texnum]);
Вам правда скобки не очень нужны. :)

2022-07-16 15:34 UTC, a1batross commented on ref_gl/gl_image.c
> -/*
Верните комментарии! 

Да, мне тоже их бывает лень ставить и тем более прописывать что функция вообще делает, но когда-нибудь мы сделаем парсер к дохуягену или наоборот сконвертируем в его формат. И вообще это эстетично, по-кваковcки. :)

2022-07-16 15:34 UTC, a1batross commented on ref_gl/gl_image.c
> -	case PF_BC6H_SIGNED:
????

2022-07-16 15:34 UTC, a1batross commented on ref_gl/gl_image.c
> -	case GL_COMPRESSED_SRGB_ALPHA_BPTC_UNORM_ARB:
????????

2022-07-16 15:34 UTC, a1batross commented on ref_gl/gl_image.c
> -		case PF_BC6H_SIGNED: tex->format = GL_COMPRESSED_RGB_BPTC_SIGNED_FLOAT_ARB; break;
Вот поэтому я говорю ребейзить. Так случайно не потеряешь то, что добавилось даже после патчсета растянутого на год.

2022-07-16 15:34 UTC, a1batross commented on ref_gl/gl_image.c
> -void R_TextureList_f( void )
А ну верни!

2022-07-16 15:34 UTC, a1batross commented on ref_gl/gl_image.c
> +	gEngfuncs.Con_Printf( "Found standart textures.\n" );
Движок их всегда вам выдаст. Я не думаю что есть смысл в таких сообщениях.

2022-07-16 15:34 UTC, a1batross commented on ref_gl/gl_image.c
> +	// FIXME
FIXME :)

2022-07-16 15:34 UTC, a1batross commented on ref_gl/gl_local.h
> +	qboolean used;
Если честно, с текстурным менеджером в движке я мало понимаю зачем тут хранить копию текстуры.

Можно было бы в resman держать что-то типа void *refdata, ref дает движку желаемый размер памяти. Так же как серверная библиотека передает движку размер класса, движок аллоцирует память и возвращает указатель серверке. А на самом деле оно всё внутри `edict_t::pvPrivateData`.

2022-07-16 15:34 UTC, a1batross commented on ref_soft/r_image.c
> -void R_TextureList_f( void )
Верните! [2]

2022-08-07 20:23 UTC, zgdump commented on engine/resman/texture.c
> +	Con_Reportf( "RM_LoadTexture. Name %s\n", name );
@a1batross подскажи, как быть с отладочными сообщениями? Убирать жалко, вдруг потребуется поотлаживать (кажись, во мне заговорил дед). Окружать каждый лог в `#if 0` нудно, громоздко и неудобно. Как лучше поступить?

2022-08-07 20:26 UTC, zgdump commented on engine/resman/texture.c
> +	ref_interface_t* ref;
@a1batross считаю, да, нужным. `ref.dllFuncs` находится в `engine/client`, а менеджер текстур находится в `engine/common`. Не хочу создавать зависимость common от client ради одного индирекшина

2022-08-07 20:33 UTC, zgdump commented on engine/resman/texture.c
> +int CreateDlightTexture( void )
Я её перенёс за компанию :)
Если она используется только в ref_gl и никто извне её не запрашивает, могу удалить у себя и восстановить в рендере

2022-08-07 20:34 UTC, zgdump commented on ref_gl/gl_image.c
> -/*
Они были малоинформативными и я без задней мысли их снёс. Тереть так тереть. Нужны, могу восстановить

2022-08-07 20:35 UTC, zgdump commented on ref_gl/gl_image.c
> -		case PF_BC6H_SIGNED: tex->format = GL_COMPRESSED_RGB_BPTC_SIGNED_FLOAT_ARB; break;
@a1batross как мне теперь восстановить утерянные изменения? Руками? Или лучше ревертнуть мёрж и сделать ребейз?

2022-08-07 20:37 UTC, zgdump commented on engine/resman/texture.c
> +int CreateDlightTexture( void )
Там ещё и с небо бы перенести, оно всё ещё осталось в рендере

2022-08-07 20:39 UTC, a1batross commented on ref_gl/gl_image.c
> -/*
Восстанавливай. Когда-нибудь мы напишем дохугено-подобный парсер подобных комментов. :)

Где сможешь заодно можешь описания придумать.

2022-08-07 20:40 UTC, a1batross commented on engine/resman/texture.c
> +int CreateDlightTexture( void )
Ну, пусть будет. Вроде ref_soft аналогично её использует.

2022-08-07 20:41 UTC, a1batross commented on engine/resman/texture.c
> +	Con_Reportf( "RM_LoadTexture. Name %s\n", name );
Скорее всего ничего, что не сможет сделать отладчик, уже не будет. :)

Ближе к финальной версии предлагаю все же убрать.

2022-08-07 21:20 UTC, a1batross commented on engine/resman/texture.c
> +	ref_interface_t* ref;
@zgdump #ifdef XASH_DEDICATED никто не запрещал в common/.

Тем более, горячая замена рендерера скорее всего будет конфликтовать с #947. А выгрузку библиотек мы скорее всего будем убирать.

2022-08-08 14:14 UTC, a1batross commented
А ты движок вообще собираешь после своих коммитов?

Потому что я ребейзнул и ничего не собирается. По крайней мере под Linux.

2022-08-08 14:29 UTC, a1batross commented
Разреши коммитить в твою ветку мейнтейнерам. На гитхабе есть где-то галочка.

Пока залил исправления в `resman_texture` в нашем репозитории.

2022-08-08 16:02 UTC, zgdump commented
> Разреши коммитить в твою ветку мейнтейнерам. На гитхабе есть где-то галочка.
> 
> Пока залил мелкие исправления в `resman_texture` в нашем репозитории. НЕ МЕРЖИ ИХ, ПОТОМУ ЧТО ЭТО РЕБЕЙЗ!!11111111

Да я и сам хотел ребейзнуть, но случайно разнёс ветку в попытках починить. Думал отложить синхронизацию с мастером до лучших времён...) Я руками там восстановил утерянные изменения в gl_image.c, а больше ничего критичного вроде бы и нет

2022-08-08 16:11 UTC, zgdump commented on ref_gl/gl_image.c
> -		case PF_BC6H_SIGNED: tex->format = GL_COMPRESSED_RGB_BPTC_SIGNED_FLOAT_ARB; break;
Восстановил руками

2022-08-08 16:17 UTC, zgdump commented
Основную пачку разгрёб.

Осталось...

- [ ] Вернуть R_ShowTextures в ref_api
- [ ] Поправить оформление в texturelib
- [ ] Прокомментировать счётчик текстур в texturelib
- [ ] Понять, зачем мы храним оригинал текстуры и нужно ли его оставлять в ref

Ohhhhh...

2022-08-08 17:10 UTC, a1batross commented
Возьми мою ветку, там под линукс собирается теперь.

Эту просто перепиши форспушем. :)

2022-08-09 00:23 UTC, zgdump commented
> Возьми мою ветку, там под линукс собирается теперь.

Какую твою?

> Эту просто перепиши форспушем. :)

Эт шо, мне переносить всё здесь напатченное в 30+ файлах рученьками переносить на другую ветку? Ий историю коммитов потеряю, и долгое

2022-08-09 00:31 UTC, a1batross commented
@zgdump resman_texture. https://github.com/FWGS/xash3d-fwgs/tree/resman_texture

Зафетчи fwgs remote, чтобы ветка была.

>Эт шо, мне переносить всё здесь напатченное в 30+ файлах рученьками переносить на другую ветку? Ий историю коммитов потеряю, и долгое

Нет. Закоммити что ты сделал в свою, возьми мою ветку, черрипикни в неё то что ты накоммитил в своей и форспушни поверх.

2023-03-27 01:09 UTC, a1batross commented
@zgdump any news on this? I really would like to see this upstreamed.

2023-04-23 09:55 UTC, 0x4E69676874466F78 commented
Последняя его TODO:
```
1. Вернуть R_ShowTextures в ref api
2. Поправить оформление в texturelib
3. Прикрутить текстуры неба
4. Протестировать текстуры-заглушки
5. Решить, стоит ли оставлять оригинал текстуры в ref_ и вообще для чего оно использовалось раньше
```
Похоже zgdump не в состоянии уже закончить, но возможно это будет по пути @w23.

2025-01-15 11:43 UTC, vklachkov commented
Спустя два года, закрою PR. У меня не дошли руки его завершить тогда, а сейчас его и вовсе нужно переписывать с нуля.

2025-01-15 11:43 UTC, closed without merging